import streamlit as st
import plotly.express as px
import pandas as pd
import os

# Import our custom modules
from vector_store import setup_vector_db, get_relevant_schema
from core_pipeline import (
    get_sql_query, 
    execute_query_safely, 
    calculate_statistics, 
    generate_plotly_code,
    generate_narrative_report
)

# Configuration
DB_PATH = 'sales_data.sqlite'

# Initialize Vector DB (Runs once and caches)
@st.cache_resource
def init_system():
    return setup_vector_db(DB_PATH)

st.set_page_config(page_title="Narrative BI Engine", page_icon="📊", layout="wide")
st.title("📊 Narrative BI Engine")
st.markdown("Ask business questions and get data-driven insights instantly.")

# System Setup
collection = init_system()

user_question = st.text_input("Ask your business question:", placeholder="e.g., What is the total sales amount in the North region?")

if st.button("Analyze") and user_question:
    with st.spinner("Analyzing data..."):
        
        # 1. Retrieve Schema
        schema = get_relevant_schema(collection, user_question)
        
        # 2. LLM Call 1: Get SQL
        sql_query = get_sql_query(user_question, schema)
        
        # 3. Python Deterministic Execution
        df, error = execute_query_safely(DB_PATH, sql_query)
        
        if error:
            st.error(f"Database execution error: {error}")
            st.code(sql_query, language="sql")
        elif df is None or df.empty:
            st.warning("Query executed successfully, but no data was found.")
            st.code(sql_query, language="sql")
        else:
            # 4. Calculate Stats & LLM Calls for Chart and Narrative
            stats = calculate_statistics(df)
            
            # The Vanna Way: Ask LLM to write Plotly code
            plotly_code = generate_plotly_code(user_question, df)
            
            # Get Narrative
            narrative = generate_narrative_report(user_question, df, stats)
            
            # --- Display Results ---
            st.subheader("📝 Executive Summary")
            st.info(narrative)
            
            # Safely execute the LLM-generated Python code
            st.subheader("📈 Data Visualization")
            if len(df.columns) >= 2:
                # Create a local environment for the exec() function to run safely
                local_vars = {'df': df, 'px': px, 'pd': pd}
                try:
                    # Run the code generated by LLM
                    exec(plotly_code, globals(), local_vars)
                    
                    # Extract the 'fig' variable created by the LLM code
                    fig = local_vars.get('fig')
                    if fig:
                        st.plotly_chart(fig, use_container_width=True)
                    else:
                        st.warning("The AI generated code, but failed to create a 'fig' object.")
                except Exception as e:
                    st.error(f"Failed to render chart. Code execution error: {e}")
                    with st.expander("View generated code"):
                        st.code(plotly_code, language="python")
            else:
                st.write("Not enough data columns to generate a meaningful chart.")
            
            # Debugging / Under the hood
            with st.expander("🔍 Under the Hood (Raw Data & Queries)"):
                st.write("**Generated SQL Query:**")
                st.code(sql_query, language="sql")
                
                st.write("**Generated Plotly Code:**")
                st.code(plotly_code, language="python")
                
                st.write("**Extracted DataFrame:**")
                st.dataframe(df)